# fly.toml app configuration file generated for bbcguild-test on 2025-06-08T02:00:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bbcguild'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
