# fly.toml app configuration file generated for bbcguild-test on 2025-07-11T14:23:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bbcguild'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[restart]]
  policy = 'always'
  retries = 10

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
